## Importando bibliotecas

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
#import scikit-learn as sklearn

## Importando o conjunto de dados

In [4]:
dataset = pd.read_csv('D:/Transdimension/Order 81004901 Comparison of Machine Learning Models/csv_result-Autism-Adult-Data.csv')
dataset.pop('ethnicity')
dataset.pop('id')
dataset.pop('used_app_before')
dataset.pop('result')
dataset.pop('age_desc')
dataset.pop('relation')
dataset.pop('contry_of_res')
dataset = dataset.drop([62,91])

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

pd.DataFrame(X)

0  1  2  3  4  5  6  7  8  9   10 11   12   13
0    1  1  1  1  0  0  1  1  0  0  26  f   no   no
1    1  1  0  1  0  0  0  1  0  1  24  m   no  yes
2    1  1  0  1  1  0  1  1  1  1  27  m  yes  yes
3    1  1  0  1  0  0  1  1  0  1  35  f   no  yes
4    1  0  0  0  0  0  0  1  0  0  40  f   no   no
..  .. .. .. .. .. .. .. .. .. ..  .. ..  ...  ...
697  0  1  0  1  1  0  1  1  1  1  25  f   no   no
698  1  0  0  0  0  0  0  1  0  1  34  m   no   no
699  1  0  1  1  1  0  1  1  0  1  24  f   no   no
700  1  0  0  1  1  0  1  0  1  1  35  m   no   no
701  1  0  1  1  1  0  1  1  1  1  26  f   no   no

[702 rows x 14 columns]

## One Hot Encoding conjunto de dados sobre pacientes

In [7]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(categories = 'auto'), [11,12,13])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
pd.DataFrame(X)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15  16
0    1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  0  0  1  1  0  0  26
1    0.0  1.0  1.0  0.0  0.0  1.0  1  1  0  1  0  0  0  1  0  1  24
2    0.0  1.0  0.0  1.0  0.0  1.0  1  1  0  1  1  0  1  1  1  1  27
3    1.0  0.0  1.0  0.0  0.0  1.0  1  1  0  1  0  0  1  1  0  1  35
4    1.0  0.0  1.0  0.0  1.0  0.0  1  0  0  0  0  0  0  1  0  0  40
..   ...  ...  ...  ...  ...  ... .. .. .. .. .. .. .. .. .. ..  ..
697  1.0  0.0  1.0  0.0  1.0  0.0  0  1  0  1  1  0  1  1  1  1  25
698  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  0  0  0  0  1  0  1  34
699  1.0  0.0  1.0  0.0  1.0  0.0  1  0  1  1  1  0  1  1  0  1  24
700  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  1  1  0  1  0  1  1  35
701  1.0  0.0  1.0  0.0  1.0  0.0  1  0  1  1  1  0  1  1  1  1  26

[702 rows x 17 columns]

## One Hot Encoding no conjunto de dados de resultado

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
###
pd.DataFrame(y)

0
0    0
1    0
2    1
3    0
4    0
..  ..
697  1
698  0
699  1
700  0
701  1

[702 rows x 1 columns]

## Dividindo os dados em conjuntos de treino e teste

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Escalonando os dados

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 16:] = sc.fit_transform(X_train[:, 16:])
X_test[:, 16:] = sc.transform(X_test[:, 16:])

In [12]:
pd.DataFrame(X_train)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15        16
0    0.0  1.0  1.0  0.0  1.0  0.0  0  0  0  1  0  0  1  0  0  0 -0.617938
1    0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  0  1  1  1  1  1  0 -1.035353
2    1.0  0.0  1.0  0.0  1.0  0.0  1  0  0  0  1  0  1  1  0  1 -0.617938
3    1.0  0.0  1.0  0.0  1.0  0.0  1  0  1  1  1  1  0  1  1  0  2.512675
4    0.0  1.0  1.0  0.0  1.0  0.0  0  0  0  0  0  0  0  1  0  0 -0.617938
..   ...  ...  ...  ...  ...  ... .. .. .. .. .. .. .. .. .. ..       ...
556  1.0  0.0  1.0  0.0  1.0  0.0  0  0  0  0  0  1  0  1  0  0 -1.035353
557  0.0  1.0  1.0  0.0  0.0  1.0  0  1  0  1  0  0  0  1  0  0  0.216892
558  0.0  1.0  1.0  0.0  1.0  0.0  0  0  0  0  0  0  1  0  0  1 -0.200523
559  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  1  1  1  1  1  1  1  -1.24406
560  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  0  1  0  1  1  0  1 -0.096169

[561 rows x 17 columns]

In [13]:
pd.DataFrame(X_test)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15        16
0    0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  0  1  1  1 -0.513584
1    1.0  0.0  1.0  0.0  1.0  0.0  1  0  0  0  1  0  0  1  0  1  0.112538
2    0.0  1.0  1.0  0.0  0.0  1.0  1  1  1  1  1  1  1  1  1  1  1.573491
3    1.0  0.0  1.0  0.0  1.0  0.0  1  0  0  0  1  0  1  1  0  0  -0.40923
4    0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  1  0  0  0  0  0  1  0.947368
..   ...  ...  ...  ...  ...  ... .. .. .. .. .. .. .. .. .. ..       ...
136  1.0  0.0  1.0  0.0  1.0  0.0  1  0  0  0  1  0  1  1  0  0  -0.40923
137  1.0  0.0  1.0  0.0  1.0  0.0  1  1  0  1  1  1  1  1  1  1   2.09526
138  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  1  1  1  0  0  0  0  1.886552
139  1.0  0.0  1.0  0.0  1.0  0.0  1  1  0  1  0  0  0  0  0  1 -0.930999
140  0.0  1.0  0.0  1.0  1.0  0.0  0  1  1  1  0  0  0  0  0  0    0.4256

[141 rows x 17 columns]

# Modelos de classificação:

# Random Forest

## Treinando o modelo

In [14]:
## Random Forest Classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=150, criterion = 'entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=150, random_state=0)

## Fazendo os resultados do modelo



In [15]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Random Forest Classification:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Random Forest Classification:
[[100   4]
 [  1  36]]
Precisao do treino e:  1.0
Precisao do teste e:  0.9645390070921985


# Logistic Regression

## Treinando o modelo

In [17]:
## Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Fazendo os resultados do modelo

In [18]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Logistic Regression:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Logistic Regression:
[[104   0]
 [  0  37]]
Precisao do treino e:  1.0
Precisao do teste e:  1.0


# K-nearest Neighbor Intuiton

## Treinando o modelo

In [20]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 6, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

## Fazendo os resultados do modelo

In [21]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para K-Nearest Neighbor Intuiton:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para K-Nearest Neighbor Intuiton:
[[99  5]
 [ 2 35]]
Precisao do treino e:  0.9768270944741533
Precisao do teste e:  0.950354609929078


# Support Vector Machine

## Treinando o modelo

In [23]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Fazendo os resultados do modelo

In [24]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Support Vector Machine:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Support Vector Machine:
[[104   0]
 [  0  37]]
Precisao do treino e:  1.0
Precisao do teste e:  1.0


# Decision Tree

## Treinando o modelo

In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Fazendo os resultados do modelo

In [27]:
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Decision Tree:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Decision Tree:
[[100   4]
 [  3  34]]
Precisao do treino e:  1.0
Precisao do teste e:  0.950354609929078


# Kernel SVM

## Treinando o modelo

In [29]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Fazendo os resultados do modelo

In [30]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Kernel SVM:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Kernel SVM:
[[100   4]
 [  2  35]]
Precisao do treino e:  0.9982174688057041
Precisao do teste e:  0.9574468085106383


# Naive Bayes

## Treinando o modelo (Gaussiano)

In [32]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Fazendo os resultados do modelo (Gaussiano)

In [33]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão (Gaussiano)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Naive Bayes (Gaussiano):")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Naive Bayes (Gaussiano):
[[98  6]
 [ 0 37]]
Precisao do treino e:  0.9393939393939394
Precisao do teste e:  0.9574468085106383


## Treinando o modelo (Bernoulli)

In [35]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

## Fazendo os resultados do modelo (Bernoulli)

In [36]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão (Bernoulli)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Naive Bayes (Bernoulli):")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Naive Bayes (Bernoulli):
[[99  5]
 [ 0 37]]
Precisao do treino e:  0.9590017825311943
Precisao do teste e:  0.9645390070921985


In [39]:
import numpy as np
from sklearn.metrics import matthews_corrcoef
#calculate Matthews correlation coefficient
matthews_corrcoef(y_test, y_pred)

0.9157504578753435