## Importando bibliotecas

In [39]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import (
    f1_score
)

## Importando o conjunto de dados

In [40]:
dataset = pd.read_csv('D:/Transdimension/Order 81004901 Comparison of Machine Learning Models/csv_result-Autism-Child-Data.csv')
dataset.pop('ethnicity')
dataset.pop('id')
dataset.pop('used_app_before')
dataset.pop('result')
dataset.pop('age_desc')
dataset.pop('relation')
dataset.pop('contry_of_res')
dataset = dataset.drop([32, 65, 126, 138])

In [41]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#pd.DataFrame(X)
dataset

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           1         1         0         0         1         1         0   
1           1         1         0         0         1         1         0   
2           1         1         0         0         0         1         1   
3           0         1         0         0         1         1         0   
4           1         1         1         1         1         1         1   
..        ...       ...       ...       ...       ...       ...       ...   
287         1         1         1         1         1         1         1   
288         1         0         0         0         1         0         1   
289         1         0         1         1         1         1         1   
290         1         1         1         0         1         1         1   
291         0         0         1         0         1         0         1   

     A8_Score  A9_Score  A10_Score age gender jundice austim Class/ASD  
0           1         0          0   6      m      no     no        NO  
1           1         0          0   6      m      no     no        NO  
2           1         0          0   6      m      no     no        NO  
3           0         0          1   5      f     yes     no        NO  
4           1         1          1   5      m     yes     no       YES  
..        ...       ...        ...  ..    ...     ...    ...       ...  
287         1         1          1   7      f     yes    yes       YES  
288         0         0          1   7      f     yes    yes        NO  
289         0         0          1   4      m      no     no       YES  
290         1         1          1   4      m      no     no       YES  
291         0         0          0   4      f      no     no        NO  

[288 rows x 15 columns]

## One Hot Encoding conjunto de dados sobre pacientes

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(categories = 'auto'), [11,12,13])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [43]:
pd.DataFrame(X)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15 16
0    0.0  1.0  1.0  0.0  1.0  0.0  1  1  0  0  1  1  0  1  0  0  6
1    0.0  1.0  1.0  0.0  1.0  0.0  1  1  0  0  1  1  0  1  0  0  6
2    0.0  1.0  1.0  0.0  1.0  0.0  1  1  0  0  0  1  1  1  0  0  6
3    1.0  0.0  0.0  1.0  1.0  0.0  0  1  0  0  1  1  0  0  0  1  5
4    0.0  1.0  0.0  1.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1  5
..   ...  ...  ...  ...  ...  ... .. .. .. .. .. .. .. .. .. .. ..
283  1.0  0.0  0.0  1.0  0.0  1.0  1  1  1  1  1  1  1  1  1  1  7
284  1.0  0.0  0.0  1.0  0.0  1.0  1  0  0  0  1  0  1  0  0  1  7
285  0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  1  1  1  1  0  0  1  4
286  0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  0  1  1  1  1  1  1  4
287  1.0  0.0  1.0  0.0  1.0  0.0  0  0  1  0  1  0  1  0  0  0  4

[288 rows x 17 columns]

## One Hot Encoding no conjunto de dados de resultado

In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
###
pd.DataFrame(y)

0
0    0
1    0
2    0
3    0
4    1
..  ..
283  1
284  0
285  1
286  1
287  0

[288 rows x 1 columns]

## Dividindo os dados em conjuntos de treino e teste

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Escalonando os dados

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 16:] = sc.fit_transform(X_train[:, 16:])
X_test[:, 16:] = sc.transform(X_test[:, 16:])

In [47]:
pd.DataFrame(X_train)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15        16
0    0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  0  1  0  1  1  0  1 -0.159099
1    1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1 -0.159099
2    1.0  0.0  1.0  0.0  1.0  0.0  1  0  1  1  1  1  1  1  1  1 -1.000314
3    0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1  1.943938
4    0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  0  1  0  1  1  0  0 -0.579707
..   ...  ...  ...  ...  ...  ... .. .. .. .. .. .. .. .. .. ..       ...
225  0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  0  1  1  0  0  0  0 -1.000314
226  0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  0  0  1  1  0.682116
227  0.0  1.0  1.0  0.0  0.0  1.0  0  1  1  0  1  0  0  0  0  1 -1.000314
228  1.0  0.0  0.0  1.0  1.0  0.0  1  0  1  1  1  1  0  0  1  1 -0.159099
229  0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  1  1  0  0  0  0  0  0.682116

[230 rows x 17 columns]

In [48]:
pd.DataFrame(X_test)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15        16
0   0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  0  0  1  0  0  0  0 -0.159099
1   0.0  1.0  0.0  1.0  1.0  0.0  1  1  1  0  1  0  1  1  1  1 -1.000314
2   0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1 -0.159099
3   0.0  1.0  0.0  1.0  1.0  0.0  0  1  1  0  1  1  0  0  0  1 -1.000314
4   1.0  0.0  0.0  1.0  1.0  0.0  0  1  1  0  0  1  0  1  1  1 -1.000314
5   1.0  0.0  0.0  1.0  1.0  0.0  0  1  1  0  1  1  0  0  0  0 -1.000314
6   0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  0 -1.000314
7   0.0  1.0  0.0  1.0  1.0  0.0  0  1  1  0  1  1  0  1  0  1  0.261508
8   0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1  0.682116
9   0.0  1.0  1.0  0.0  1.0  0.0  1  1  0  1  0  0  0  0  0  0 -1.000314
10  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  0  1  0  1  0  0  0 -0.579707
11  1.0  0.0  0.0  1.0  1.0  0.0  0  1  1  1  1  1  1  1  1  1 -0.579707
12  0.0  1.0  0.0  1.0  1.0  0.0  0  1  1  1  1  1  1  1  1  1 -1.000314
13  0.0  1.0  1.0  0.0  1.0  0.0  0  1  1  0  1  1  0  0  0  1 -0.579707
14  0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  1  0  0  0  1  0  1  0.682116
15  1.0  0.0  0.0  1.0  0.0  1.0  1  0  0  0  1  0  1  0  0  1  0.261508
16  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  1  1  1  1  1  1  1  1.523331
17  1.0  0.0  1.0  0.0  1.0  0.0  0  0  1  0  1  0  1  0  0  0 -1.000314
18  0.0  1.0  0.0  1.0  1.0  0.0  1  0  1  0  1  0  1  0  1  1 -1.000314
19  1.0  0.0  1.0  0.0  1.0  0.0  1  0  1  1  1  0  1  1  1  1  0.261508
20  0.0  1.0  1.0  0.0  0.0  1.0  0  1  0  1  1  1  1  0  1  1  1.102723
21  0.0  1.0  0.0  1.0  1.0  0.0  1  0  1  0  1  1  1  0  0  1 -0.159099
22  0.0  1.0  1.0  0.0  1.0  0.0  0  1  0  1  0  1  0  0  1  1  1.523331
23  0.0  1.0  0.0  1.0  1.0  0.0  1  0  1  0  1  0  1  0  1  1 -0.159099
24  0.0  1.0  1.0  0.0  1.0  0.0  0  1  0  0  0  1  1  1  0  0  1.943938
25  0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  1  1  1  0  1  1  1  0.682116
26  0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  0  0  1  1 -0.159099
27  0.0  1.0  0.0  1.0  1.0  0.0  0  1  1  1  1  1  1  0  0  1 -1.000314
28  1.0  0.0  0.0  1.0  1.0  0.0  1  0  1  1  0  1  1  1  0  1 -1.000314
29  0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1  1.102723
30  0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  0  0  0  1  0  1  0 -0.159099
31  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  0  0  0  1.943938
32  0.0  1.0  1.0  0.0  0.0  1.0  0  0  1  0  1  1  0  1  0  1 -1.000314
33  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  0  1  0  0  0  0 -0.579707
34  0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  1  1  1  1  1  1  1 -0.579707
35  0.0  1.0  0.0  1.0  1.0  0.0  0  1  0  1  1  0  1  1  0  1  1.102723
36  0.0  1.0  1.0  0.0  0.0  1.0  0  0  1  1  0  0  0  0  0  0  0.261508
37  0.0  1.0  0.0  1.0  1.0  0.0  1  1  1  1  1  1  0  1  0  1 -1.000314
38  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  0  0 -0.579707
39  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  0  1  0  0  0  0  1 -1.000314
40  0.0  1.0  1.0  0.0  1.0  0.0  0  0  0  1  1  1  1  1  1  0 -0.579707
41  0.0  1.0  1.0  0.0  1.0  0.0  1  0  0  1  1  1  1  0  1  1  0.261508
42  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1 -1.000314
43  0.0  1.0  1.0  0.0  0.0  1.0  1  0  1  1  1  1  0  1  0  1 -0.579707
44  0.0  1.0  1.0  0.0  0.0  1.0  1  1  1  1  1  0  1  1  1  1  0.682116
45  1.0  0.0  0.0  1.0  1.0  0.0  0  0  1  0  1  1  1  1  1  1 -1.000314
46  1.0  0.0  1.0  0.0  0.0  1.0  0  1  0  0  0  1  0  0  0  1  1.102723
47  0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  0  1  1  1  0  1  1  0.682116
48  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  0  1  1  1  1  1  1.943938
49  0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  0  1  1  1  1  0  1  1.943938
50  0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  0  1  0  0  0  0  0 -1.000314
51  1.0  0.0  1.0  0.0  1.0  0.0  0  1  0  1  1  1  1  1  1  1  1.523331
52  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  0  1  1  0  0  1  1  1.523331
53  0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  0  1  1  1  1  1  1 

# Modelos de classificação:

# Random Forest

## Treinando o modelo

In [27]:
## Random Forest Classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=190, criterion = 'entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=190, random_state=0)

## Fazendo os resultados do modelo

In [28]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Random Forest Classification:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Random Forest Classification:
[[25  3]
 [ 1 29]]
Precisao do treino e:  1.0
Precisao do teste e:  0.9310344827586207


In [31]:
f1score = f1_score(y_test, y_pred)
f1score

0.9354838709677419

# Logistic Regression

## Treinando o modelo

In [50]:
## Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Fazendo os resultados do modelo

In [51]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Logistic Regression:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Logistic Regression:
[[27  1]
 [ 0 30]]
Precisao do treino e:  1.0
Precisao do teste e:  0.9827586206896551


In [53]:
f1score = f1_score(y_test, y_pred)
f1score

0.9836065573770492

# K-nearest Neighbor Intuiton

## Treinando o modelo

In [54]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 150, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=150)

## Fazendo os resultados do modelo

In [55]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para K-Nearest Neighbor Intuiton:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para K-Nearest Neighbor Intuiton:
[[21  7]
 [ 0 30]]
Precisao do treino e:  0.8826086956521739
Precisao do teste e:  0.8793103448275862


In [57]:
f1score = f1_score(y_test, y_pred)
f1score

0.8955223880597014

# Support Vector Machine

## Treinando o modelo

In [58]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Fazendo os resultados do modelo

In [59]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Support Vector Machine:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Support Vector Machine:
[[28  0]
 [ 0 30]]
Precisao do treino e:  1.0
Precisao do teste e:  1.0


In [61]:
f1score = f1_score(y_test, y_pred)
f1score

1.0

# Decision Tree

## Treinando o modelo

In [62]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Fazendo os resultados do modelo

In [63]:
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Decision Tree:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Decision Tree:
[[23  5]
 [ 2 28]]
Precisao do treino e:  1.0
Precisao do teste e:  0.8793103448275862


In [65]:
f1score = f1_score(y_test, y_pred)
f1score

0.888888888888889

# Kernel SVM

## Treinando o modelo

In [66]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Fazendo os resultados do modelo

In [67]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Kernel SVM:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Kernel SVM:
[[27  1]
 [ 2 28]]
Precisao do treino e:  0.9956521739130435
Precisao do teste e:  0.9482758620689655


In [69]:
f1score = f1_score(y_test, y_pred)
f1score

0.9491525423728815

# Naive Bayes

## Treinando o modelo (Gaussiano)

In [70]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Fazendo os resultados do modelo (Gaussiano)

In [71]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão (Gaussiano)

In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Naive Bayes:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Naive Bayes:
[[25  3]
 [ 7 23]]
Precisao do treino e:  0.9
Precisao do teste e:  0.8275862068965517


In [73]:
f1score = f1_score(y_test, y_pred)
f1score

0.8214285714285715

## Treinando o modelo (Bernoulli)

In [74]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

## Fazendo os resultados do modelo (Bernoulli)

In [75]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão (Bernoulli)

In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Naive Bayes (Bernoulli):")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Naive Bayes (Bernoulli):
[[27  1]
 [ 1 29]]
Precisao do treino e:  0.9608695652173913
Precisao do teste e:  0.9655172413793104


In [77]:
f1score = f1_score(y_test, y_pred)
f1score

0.9666666666666667

In [ ]:
import numpy as np
from sklearn.metrics import matthews_corrcoef
#calculate Matthews correlation coefficient
matthews_corrcoef(y_test, y_pred)

0.930952380952381

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 115, in _read_from_self
 

In [ ]:

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
#
# Create an instance of Pipeline
#
pipeline = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=100, max_depth=4))
#
# Pass instance of pipeline and training and test data set
# cv=10 represents the StratifiedKFold with 10 folds
#
scores = cross_val_score(pipeline, X=X_train, y=y_train, cv=5, n_jobs=1)
 
print('Cross Validation accuracy scores: %s' % scores)
 
print('Cross Validation accuracy: %.3f +/- %.3f' % (np.mean(scores),np.std(scores)))