## Importando bibliotecas

In [36]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import (
    f1_score
)

## Importando o conjunto de dados

In [37]:
dataset = pd.read_csv('D:/Transdimension/Order 81004901 Comparison of Machine Learning Models/csv_result-Autism-Adolescent-Data.csv')
dataset.pop('ethnicity')
dataset.pop('id')
dataset.pop('used_app_before')
dataset.pop('result')
dataset.pop('age_desc')
dataset.pop('relation')
dataset.pop('contry_of_res')

0             Austria
1             Austria
2       AmericanSamoa
3      United Kingdom
4             Albania
            ...      
99           Anguilla
100             India
101    United Kingdom
102    United Kingdom
103             India
Name: contry_of_res, Length: 104, dtype: object

In [38]:
pd.DataFrame(dataset)

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           0         0         0         1         1         1         1   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         1         1         1         1         1         0   
4           1         1         1         1         1         1         1   
..        ...       ...       ...       ...       ...       ...       ...   
99          0         1         1         1         0         1         1   
100         1         0         1         0         0         0         0   
101         1         0         0         1         1         1         1   
102         1         1         0         1         1         0         0   
103         1         0         1         0         0         1         1   

     A8_Score  A9_Score  A10_Score  age gender jundice austim Class/ASD  
0           1         1          0   15      m     yes    yes        NO  
1           0         1          1   15      m      no     no        NO  
2           0         1          1   12      f      no     no        NO  
3           1         1          0   14      f      no     no       YES  
4           0         0          0   16      f      no     no       YES  
..        ...       ...        ...  ...    ...     ...    ...       ...  
99          0         1          0   16      f      no     no        NO  
100         1         0          1   16      m      no     no        NO  
101         1         1          1   12      f      no     no       YES  
102         0         1          1   13      f      no     no        NO  
103         1         1          0   12      m      no     no        NO  

[104 rows x 15 columns]

In [39]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

pd.DataFrame(X)

0  1  2  3  4  5  6  7  8  9   10 11   12   13
0    0  0  0  1  1  1  1  1  1  0  15  m  yes  yes
1    0  0  0  0  0  0  0  0  1  1  15  m   no   no
2    0  0  0  0  0  0  0  0  1  1  12  f   no   no
3    0  1  1  1  1  1  0  1  1  0  14  f   no   no
4    1  1  1  1  1  1  1  0  0  0  16  f   no   no
..  .. .. .. .. .. .. .. .. .. ..  .. ..  ...  ...
99   0  1  1  1  0  1  1  0  1  0  16  f   no   no
100  1  0  1  0  0  0  0  1  0  1  16  m   no   no
101  1  0  0  1  1  1  1  1  1  1  12  f   no   no
102  1  1  0  1  1  0  0  0  1  1  13  f   no   no
103  1  0  1  0  0  1  1  1  1  0  12  m   no   no

[104 rows x 14 columns]

## One Hot Encoding conjunto de dados sobre pacientes

In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(categories = 'auto'), [11,12,13])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [41]:
pd.DataFrame(X)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15  16
0    0.0  1.0  0.0  1.0  0.0  1.0  0  0  0  1  1  1  1  1  1  0  15
1    0.0  1.0  1.0  0.0  1.0  0.0  0  0  0  0  0  0  0  0  1  1  15
2    1.0  0.0  1.0  0.0  1.0  0.0  0  0  0  0  0  0  0  0  1  1  12
3    1.0  0.0  1.0  0.0  1.0  0.0  0  1  1  1  1  1  0  1  1  0  14
4    1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  0  0  0  16
..   ...  ...  ...  ...  ...  ... .. .. .. .. .. .. .. .. .. ..  ..
99   1.0  0.0  1.0  0.0  1.0  0.0  0  1  1  1  0  1  1  0  1  0  16
100  0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  0  0  0  0  1  0  1  16
101  1.0  0.0  1.0  0.0  1.0  0.0  1  0  0  1  1  1  1  1  1  1  12
102  1.0  0.0  1.0  0.0  1.0  0.0  1  1  0  1  1  0  0  0  1  1  13
103  0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  0  0  1  1  1  1  0  12

[104 rows x 17 columns]

## One Hot Encoding no conjunto de dados de resultado

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
###
pd.DataFrame(y)

0
0    0
1    0
2    0
3    1
4    1
..  ..
99   0
100  0
101  1
102  0
103  0

[104 rows x 1 columns]

## Dividindo os dados em conjuntos de treino e teste

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Escalonando os dados

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 16:] = sc.fit_transform(X_train[:, 16:])
X_test[:, 16:] = sc.transform(X_test[:, 16:])

In [46]:
pd.DataFrame(X_train)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15        16
0   1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  0  0  1  1 -0.737851
1   1.0  0.0  1.0  0.0  1.0  0.0  0  1  1  1  1  1  0  1  1  0 -0.086344
2   0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  0  1  0  1.216669
3   0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  0  1  1  1  0  1  1  1.216669
4   0.0  1.0  1.0  0.0  0.0  1.0  1  1  1  0  1  0  1  0  1  0  1.216669
..  ...  ...  ...  ...  ...  ... .. .. .. .. .. .. .. .. .. ..       ...
78  0.0  1.0  1.0  0.0  1.0  0.0  1  0  1  0  0  0  0  1  0  1  1.216669
79  0.0  1.0  1.0  0.0  1.0  0.0  0  0  1  0  1  1  1  0  0  0  1.216669
80  1.0  0.0  1.0  0.0  0.0  1.0  1  0  1  1  1  0  1  1  1  0 -0.086344
81  0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  0  1  0  0  1  0 -1.389357
82  1.0  0.0  1.0  0.0  1.0  0.0  0  0  1  1  1  1  1  1  1  0  0.565162

[83 rows x 17 columns]

In [47]:
pd.DataFrame(X_test)

0    1    2    3    4    5  6  7  8  9  10 11 12 13 14 15        16
0   0.0  1.0  1.0  0.0  1.0  0.0  1  1  0  1  0  0  0  0  0  0 -1.389357
1   1.0  0.0  1.0  0.0  1.0  0.0  1  1  0  0  0  0  0  1  0  0  1.216669
2   1.0  0.0  1.0  0.0  1.0  0.0  0  0  0  0  0  0  0  0  1  1 -1.389357
3   1.0  0.0  1.0  0.0  1.0  0.0  0  0  1  1  1  1  1  1  1  1  1.216669
4   0.0  1.0  0.0  1.0  1.0  0.0  0  0  1  1  1  0  1  1  1  1  1.216669
5   1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  0  1  1  1  1  1  1 -1.389357
6   1.0  0.0  0.0  1.0  0.0  1.0  1  0  0  0  1  0  0  1  0  1 -1.389357
7   1.0  0.0  1.0  0.0  1.0  0.0  0  1  1  1  0  1  1  0  1  0  1.216669
8   0.0  1.0  1.0  0.0  1.0  0.0  0  1  0  0  0  0  0  0  0  0  0.565162
9   0.0  1.0  0.0  1.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1  1.216669
10  1.0  0.0  1.0  0.0  1.0  0.0  1  0  1  1  1  1  0  1  1  1  0.565162
11  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  0  0  1.216669
12  0.0  1.0  1.0  0.0  1.0  0.0  0  1  1  1  1  1  1  1  1  1 -0.737851
13  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  0  1  1  1 -1.389357
14  1.0  0.0  1.0  0.0  1.0  0.0  1  1  0  1  1  0  1  1  0  1  0.565162
15  1.0  0.0  1.0  0.0  1.0  0.0  1  0  1  1  1  1  0  1  1  1 -0.086344
16  1.0  0.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1  0.565162
17  0.0  1.0  1.0  0.0  1.0  0.0  1  1  1  1  1  1  1  1  1  1 -0.086344
18  0.0  1.0  0.0  1.0  1.0  0.0  1  1  1  1  1  1  1  0  1  1 -1.389357
19  0.0  1.0  0.0  1.0  0.0  1.0  1  1  1  1  1  1  0  0  0  0 -1.389357
20  0.0  1.0  1.0  0.0  1.0  0.0  0  1  1  1  1  1  1  1  1  1  1.216669

# Modelos de classificação:

# Random Forest

## Treinando o modelo

In [48]:
## Random Forest Classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=190, criterion = 'entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=190, random_state=0)

## Fazendo os resultados do modelo

In [49]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Random Forest Classification:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Random Forest Classification:
[[ 6  1]
 [ 0 14]]
Precisao do treino e:  1.0
Precisao do teste e:  0.9523809523809523


In [51]:
f1score = f1_score(y_test, y_pred)
f1score

0.9655172413793104

# Logistic Regression

## Treinando o modelo

In [52]:
## Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Fazendo os resultados do modelo

In [53]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Logistic Regression:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Logistic Regression:
[[ 7  0]
 [ 0 14]]
Precisao do treino e:  0.9879518072289156
Precisao do teste e:  1.0


In [55]:
f1score = f1_score(y_test, y_pred)
f1score

1.0

# K-nearest Neighbor Intuition



## Treinando o modelo

In [56]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

## Fazendo os resultados do modelo

In [57]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para K-Nearest Neighbor Intuiton:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para K-Nearest Neighbor Intuiton:
[[ 6  1]
 [ 0 14]]
Precisao do treino e:  0.927710843373494
Precisao do teste e:  0.9523809523809523


In [59]:
f1score = f1_score(y_test, y_pred)
f1score

0.9655172413793104

# Support Vector Machine

## Treinando o modelo

In [60]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Fazendo os resultados do modelo

In [61]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Support Vector Machine:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Support Vector Machine:
[[ 6  1]
 [ 1 13]]
Precisao do treino e:  0.9879518072289156
Precisao do teste e:  0.9047619047619048


In [63]:
f1score = f1_score(y_test, y_pred)
f1score

0.9285714285714286

# Decision Tree

## Treinando o modelo

In [64]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Fazendo os resultados do modelo

In [65]:
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Decision Tree:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Decision Tree:
[[ 5  2]
 [ 0 14]]
Precisao do treino e:  1.0
Precisao do teste e:  0.9047619047619048


In [67]:
f1score = f1_score(y_test, y_pred)
f1score

0.9333333333333333

# Kernel SVM

## Treinando o modelo

In [68]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Fazendo os resultados do modelo

In [69]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão

In [70]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Kernel SVM:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Kernel SVM:
[[ 6  1]
 [ 0 14]]
Precisao do treino e:  0.9879518072289156
Precisao do teste e:  0.9523809523809523


In [71]:
f1score = f1_score(y_test, y_pred)
f1score

0.9655172413793104

# Naive Bayes

## Treinando o modelo (Gaussiano)

In [73]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Fazendo os resultados do modelo (Gaussiano)

In [74]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão (Gaussiano)

In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Naive Bayes:")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Naive Bayes:
[[ 7  0]
 [ 3 11]]
Precisao do treino e:  0.891566265060241
Precisao do teste e:  0.8571428571428571


In [76]:
f1score = f1_score(y_test, y_pred)
f1score

0.88

## Treinando o modelo (Bernoulli)

In [77]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

## Fazendo os resultados do modelo (Bernoulli)

In [78]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Matriz de confusão (Bernoulli)

In [79]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para Naive Bayes (Bernoulli):")
print(cm)
precisao_teste = accuracy_score(y_test, y_pred)
precisao_treino = accuracy_score(y_train, classifier.predict(X_train))
print("Precisao do treino e: ", precisao_treino)
print("Precisao do teste e: ", precisao_teste)

Matriz de confusão para Naive Bayes (Bernoulli):
[[ 6  1]
 [ 0 14]]
Precisao do treino e:  0.927710843373494
Precisao do teste e:  0.9523809523809523


In [ ]:
f1score = f1_score(y_test, y_pred)
f1score

0.9655172413793104

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 115, in _read_from_self
 

In [37]:
import numpy as np
from sklearn.metrics import matthews_corrcoef
#calculate Matthews correlation coefficient
matthews_corrcoef(y_test, y_pred)

0.8944271909999159

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
#
# Create an instance of Pipeline
#
pipeline = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=100, max_depth=4))
#
# Pass instance of pipeline and training and test data set
# cv=10 represents the StratifiedKFold with 10 folds
#
scores = cross_val_score(pipeline, X=X_train, y=y_train, cv=5, n_jobs=1)
 
print('Cross Validation accuracy scores: %s' % scores)
 
print('Cross Validation accuracy: %.3f +/- %.3f' % (np.mean(scores),np.std(scores)))